#!/usr/bin/bash
LAST_TAG=$(git describe)
NEW_TAG=$(LAST_TAG=${LAST_TAG} python travis/upversion.py)

git config --global user.email "builds@travis-ci.com"
git config --global user.name "Travis CI"

git tag ${NEW_TAG} -a -m "Autogenerated version bump tag: ${NEW_TAG} from TravisCI build ${TRAVIS_BUILD_NUMBER}"

git push --quiet https://$GITHUBKEY@github.com/yahoo/fili ${NEW_TAG} > /dev/null 2>&1
